### ISSUE TITLE
Action reports success even when a workflow failed

### ISSUE THREAD

**Issue by ondrejmirtes** [WyriHaximus/github-action-wait-for-status#103]
Hi,
I'm using your awesome action to automatically merge PRs create by bots. Here's my workflow: https://github.com/phpstan/phpstan-src/blob/1.6.x/.github/workflows/merge-bot-pr.yml

The problem is that the action reports success even when a check fails, it can be seen in this PR: https://github.com/phpstan/phpstan-src/pull/1149

Here's the log of the merge workflow: https://github.com/phpstan/phpstan-src/runs/5768914566?check_suite_focus=true

Here's the workflow that failed: https://github.com/phpstan/phpstan-src/actions/runs/2070287218

I don't know what's the problem. The thing that's special about the failed workflow is that it uses reusable workflows: https://docs.github.com/en/actions/using-workflows/reusing-workflows with `workflow_call`.

**Comment by WyriHaximus** [comment]
Hey @ondrejmirtes, that is weird. Having a look at it, and for some reason I can't find the failing jobs on https://github.com/phpstan/phpstan-src/runs/5768914566?check_suite_focus=true#step:3:363 at all. Having a deeper look and will get back to you when I find something

**Comment by ondrejmirtes** [comment]
It's possible that at the beginning there are only 30 checks but that number expands later as one phase of the workflow is done and there are more jobs that have the previous one in `needs`.

**Comment by WyriHaximus** [comment]
Could be, I'm using the GitHub API for this, so maybe I need to recheck certain things again that might have changed. But that could very well be it

**Comment by WyriHaximus** [comment]
@ondrejmirtes found the issue. It's not traversing all the API pages with checks for some reason. Having a deeper look why that is.

**Comment by WyriHaximus** [comment]
Filed a PR at https://github.com/WyriHaximus/github-action-wait-for-status/pull/106 hoping to test and confirm tomorrow or Friday's

**Comment by WyriHaximus** [comment]
Confirmed it's now iterating over all checks and finds the failing check as it should:
![image](https://user-images.githubusercontent.com/147145/163798009-1a3a369f-af4d-4206-bea3-c973644824b6.png)
![image](https://user-images.githubusercontent.com/147145/163797979-a3909e1d-45ae-4b19-bf12-7719071dda50.png)

**Comment by ondrejmirtes** [comment]
Awesome! Do I get this automatically once you create a release or is there action (pun intended) required? 😊

**Comment by WyriHaximus** [comment]
As long as you use it with `@v1` you'll get it automatically 😎

**Comment by ondrejmirtes** [comment]
Great, I do :)

**Comment by WyriHaximus** [comment]
[`v1.5.01](https://github.com/WyriHaximus/github-action-wait-for-status/releases/tag/v1.5.0) is out with the fix for this in it

**Comment by WyriHaximus** [comment]
@ondrejmirtes Please let me know if this works correctly for you now

**Comment by ondrejmirtes** [comment]
I'll let you know if something gets merged by error (if the action doesn't do what it's supposed to :))

Thank you!
