### ISSUE TITLE
Action running indefinitely

### ISSUE THREAD

**Issue by ondrejmirtes** [WyriHaximus/github-action-wait-for-status#111]
Hi, the new version runs indefinitely even when all other statuses are successful.

Here's an example PR: https://github.com/phpstan/phpstan-src/pull/1246

Here's the action: https://github.com/phpstan/phpstan-src/runs/6167297428?check_suite_focus=true

All statuses were successful after a few minutes but the action has been running for the last 5 and half hours.

**Comment by WyriHaximus** [comment]
Weird, having a look

**Comment by WyriHaximus** [comment]
The one thing standing out in the 95MB of logs is `Check "Commit PHAR" has the following status "completed" and conclusion "skipped"` but that is supported and should be handled as a success not a failure. Going to run it against it locally and see which check is not considered done and why.

**Comment by WyriHaximus** [comment]
It just came back to me positive in 30 seconds, as if there are no issues. Maybe it's waiting on it self but can't find that in the logs (yet).

**Comment by ondrejmirtes** [comment]
It happened again this night: https://github.com/phpstan/phpstan-src/pull/1281

if there's a failure, the action can detect it immediately, but in case of all successful checks, it waits indefinitely.

**Comment by WyriHaximus** [comment]
> if there's a failure, the action can detect it immediately, but in case of all successful checks, it waits indefinitely.

That is actually really interesting, might know where to find out what is wrong now thanks :+1:

**Comment by WyriHaximus** [comment]
Created https://github.com/phpstan/phpstan-src/pull/1285 to resolve this. Will improve logging because I was following a red herring and I checked for the automerge check in the logs but couldn't find it.

**Comment by WyriHaximus** [comment]
@ondrejmirtes Seems like it's working as expected now looking at https://github.com/phpstan/phpstan-src/pull/1286, correct?

**Comment by WyriHaximus** [comment]
Also created https://github.com/WyriHaximus/github-action-wait-for-status/pull/114 to clarify this in the docs

**Comment by ondrejmirtes** [comment]
Yes it is 😊 Thank you!

**Comment by WyriHaximus** [comment]
Great to hear that, I hope my changes in #114 will prevent this issue for future users 👍

**Comment by ondrejmirtes** [comment]
Maybe the log should state the status check that it’s indefinitely waiting on, to make this more obvious?

Also an idea (please keep in mind from someone that never wrote a custom action) - wouldn’t it be possible for a custom action/workflow to set some metadata so it can recognize itself reliably and not rely on some “stringly-typed” label that needs to match and that’s easy to get wrong?

**Comment by WyriHaximus** [comment]
> Maybe the log should state the status check that it’s indefinitely waiting on, to make this more obvious?

Looking to improve on that indeed. Will start with including the ignored actions into logging so we can see what is skipped.

> Also an idea (please keep in mind from someone that never wrote a custom action) - wouldn’t it be possible for a custom action/workflow to set some metadata so it can recognize itself reliably and not rely on some “stringly-typed” label that needs to match and that’s easy to get wrong?

Will look into that, not sure how and if that is possible. But that would help a lot for sure.
