### ISSUE TITLE
Status check on completed and conclusion success not working

### ISSUE THREAD

**Issue by Andrew-Chen-Wang** [WyriHaximus/github-action-wait-for-status#38]
I think this action is getting stuck when GitHub actions returns something like this: https://github.com/SimpleJWT/drf-SimpleJWT-Vue/pull/12

in which my node CI is exiting with status completed and conclusion success. Is there any way to avoid this?

**Comment by WyriHaximus** [comment]
That's odd it shouldn't do that, I'll have a look at it

**Comment by Andrew-Chen-Wang** [comment]
Hey @WyriHaximus this may help: https://docs.github.com/en/free-pro-team@latest/rest/reference/repos#get-the-combined-status-for-a-specific-reference

Ref: https://github.community/t/how-to-set-js-tests-in-github-actions-to-output-success-for-action/138990/4

**Comment by WyriHaximus** [comment]
Hey @Andrew-Chen-Wang that only works if you wouldn't ignore anything. Might consider that if the ignore input is empty. Also beware that status and checks API's are different, so depending on which API is used to report it has to fetched using that API, making it a bit annoying. Also if the workflow this action runs in isn't ignored it will also be stuck waiting for itself

**Comment by WyriHaximus** [comment]
And looking at https://github.com/SimpleJWT/drf-SimpleJWT-Vue/blob/master/.github/workflows/automerge.yml#L16 combined with https://github.com/WyriHaximus/github-action-wait-for-status/issues/35 that might just be it

**Comment by Andrew-Chen-Wang** [comment]
Hm, sorry if I'm not understanding this, but are you saying I should change "automerge" to "worker" since that's the name of the job? I think what confused me was that the file was named automerge.yml.

**Comment by Andrew-Chen-Wang** [comment]
Oh wow, am I dumb! My test repository already noted that: https://github.com/Andrew-Chen-Wang/test-dependabot-automerge/blob/4807bb4a1af98aafd464a3dcd83a65657670835e/.github/workflows/dependabot.yml#L7-L16

**Comment by Andrew-Chen-Wang** [comment]
Yea that was exactly the reason why. Thanks!

**Comment by WyriHaximus** [comment]
Great to hear that :+1:
