### ISSUE TITLE
v1 tag not pointing at latest v1 release

### ISSUE THREAD

**Issue by RebeccaStevens** [WyriHaximus/github-action-wait-for-status#82]
Would you be able to update the v1 tag so that it is the same as the latest v1 release (currently v1.3.1)?
Then whenever a new minor/patch version is released, update that tag to point to that new release?

This will allow for simply using:

```yaml
uses: WyriHaximus/github-action-wait-for-status@v1
```

To use the latest release.

This is how the actions in https://github.com/actions work.

**Comment by WyriHaximus** [comment]
Hmm maybe I should document this better, but the `v1` tag pulls in the `v1` docker image, which does get updated. If you look at the sha on [`v1`](https://hub.docker.com/layers/wyrihaximusgithubactions/wait-for-status/v1/images/sha256-4b6466b75af89341a108e94741a220d95693c7ee850f186c3cafd72b72b62ab1?context=explore), [`v1.3`](https://hub.docker.com/layers/wyrihaximusgithubactions/wait-for-status/v1.3/images/sha256-4b6466b75af89341a108e94741a220d95693c7ee850f186c3cafd72b72b62ab1?context=explore), and [`v1.3.11](https://hub.docker.com/layers/wyrihaximusgithubactions/wait-for-status/v1.3.1/images/sha256-4b6466b75af89341a108e94741a220d95693c7ee850f186c3cafd72b72b62ab1?context=explore). You'll see it's all `4b6466b75af89341a108e94741a220d95693c7ee850f186c3cafd72b72b62ab1`, `v1.3` and `v1` are a retag of `v1.3.1`. But it might not be that obvious, and it will probably help to put that in the `v1` and `v1.3` release messages. What do you think about that?

**Comment by RebeccaStevens** [comment]
The git tags look like this to me:

`v1`'s sha is 0c2064a0a920efa6e2b8fd9d42c5f4897040b5bb
`v1.3`'s sha is c3091ad3007b360d96e503cbc2079ad79215e67e
`v1.3.1`'s sha is cef6627634df61ec55743e8d83bcfbe890b68bd4

**Comment by WyriHaximus** [comment]
Yes, and if you look at those commits you'll see the only change in there is the tag in the Dockerfile. That resolves to these versions when I posted that comment yesterday, released 1.4 a few hours later so they are out of date.

> [`v1`](https://hub.docker.com/layers/wyrihaximusgithubactions/wait-for-status/v1/images/sha256-4b6466b75af89341a108e94741a220d95693c7ee850f186c3cafd72b72b62ab1?context=explore), [`v1.3`](https://hub.docker.com/layers/wyrihaximusgithubactions/wait-for-status/v1.3/images/sha256-4b6466b75af89341a108e94741a220d95693c7ee850f186c3cafd72b72b62ab1?context=explore), and [`v1.3.1`](https://hub.docker.com/layers/wyrihaximusgithubactions/wait-for-status/v1.3.1/images/sha256-4b6466b75af89341a108e94741a220d95693c7ee850f186c3cafd72b72b62ab1?context=explore).

**Comment by RebeccaStevens** [comment]
I get it know. Sorry for the misunderstanding.

**Comment by WyriHaximus** [comment]
@RebeccaStevens No problem, just updated the release message over https://github.com/WyriHaximus/github-action-wait-for-status/releases/tag/v1 would that have clarified it? (Will update all current and future releases with that message if it does.)

**Comment by RebeccaStevens** [comment]
Sounds good.
